manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Cyboard-DigitalTailor
      url-base: https://github.com/Cyboard-DigitalTailor
    - name: urob
      url-base: https://github.com/urob
    - name: darknao
      url-base: https://github.com/darknao
    - name: kot149
      url-base: https://github.com/kot149

  projects:

    - name: zmk-keyboards
      remote: Cyboard-DigitalTailor
      revision: main
      import: config/west.yml

    - name: zmk
      remote: darknao
      revision: zmk-perkey_ug
      import: app/west.yml

    - name: zmk-scroll-snap
      remote: kot149
      revision: v1

    # urob modules
    - name: zmk-adaptive-key
      remote: urob
      revision: main
      path: modules/zmk/adaptive-key

    - name: zmk-auto-layer
      remote: urob
      revision: main
      path: modules/zmk/auto-layer

    - name: zmk-leader-key
      remote: urob
      revision: main
      path: modules/zmk/leader-key

    - name: zmk-tri-state
      remote: urob
      revision: main
      path: modules/zmk/tri-state

  self:
    path: config
